image: gradle:4.8-jdk8

stages:
  - build
  - test
  - deploy

before_script:
  - echo `pwd` # debug
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build
    - java -jar build/libs/kotlin-ktor-api-master-1.0-SNAPSHOT.jar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
